version: 2
updates:
  # Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/internal/tools/"
    schedule:
      interval: "weekly"
  # Docker
  - package-ecosystem: "docker"
    directories:
      - "/build/elasticsearch-*/"
      - "/build/rest-server/"
    schedule:
      interval: "weekly"
    groups:
      go-versions:
        applies-to: version-updates
        patterns:
          - "debian*"
          - "golang*"
  # Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
